name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PaylocityApi/PaylocityApi/
    - name: Build
      working-directory: PaylocityApi/PaylocityApi/
      run: dotnet build --no-restore
    - name: Test
      working-directory: PaylocityApi/PaylocityApi/
      run: dotnet test --no-build --verbosity normal
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.28

